version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=kubsu
      - POSTGRES_PASSWORD=kubsu
      - POSTGRES_DATABASE=kubsu
    networks:
      - mynetwork
  pythonapp:
    image: pythonapp:latest
    build: ./python_app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+psycopg://kubsu:kubsu@db:5432/kubsu
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
